In [4]:
import numpy as np

In [19]:
np_array_1= np.array([1,2,3,4])
print(np_array_1)
print(type(np_array_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
np_array_2 = np.array([[1,2,3],[4,5,6]])
print(np_array_2)

[[1 2 3]
 [4 5 6]]


In [7]:
#array 행의 수
print(np_array_2.ndim)
#array의 크기 출력
print(np_array_2.shape)

2
(2, 3)


In [8]:
#0행렬-> zeros(크기)
zero_array = np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
one_array = np.ones((3,4))
one_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
full_array = np.full((2,2),3)
full_array

array([[3, 3],
       [3, 3]])

In [10]:
#단위행렬 만드는 함수 -> eye(크기)
##행,열 갯수 다 적을 필요없음
# 하나만 넣으면 나머지는 똑같이 됨.

eye_array = np.eye(3)
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#임의의 값을 가지는 행렬 -> random.random(크기)
random_array = np.random.random((4,2))
random_array

array([[0.36119219, 0.10546498],
       [0.04941398, 0.18992885],
       [0.28548107, 0.62036953],
       [0.73697634, 0.52586819]])

In [20]:
arange_array = np.arange(10)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arange_array2 = np.arange(2,10,2)
arange_array2

array([2, 4, 6, 8])

In [22]:
## 행렬의 구조를 변경하는 함수 -> reshape(크기)
reshape_array = arange_array.reshape((2,5))
reshape_array


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
reshape_array_2 = arange_array.reshape((3,3))
reshape_array_2


ValueError: cannot reshape array of size 10 into shape (3,3)

In [24]:
#행렬연산
x = np.array([1,2,3])
y = np.array([4,5,6])


In [29]:

## 행렬의 덧셈 -> x + y / np.add(x, y)
## 행렬의 뺄셈 -> x - y / np.suntract(x, y)
## 행렬의 곱셈 -> x * y / np.multiply(x, y)
## 행렬의 나눗셈 -> x / y  /  np.divide(x, y)
print(x+y)
print(np.add(x, y))


[5 7 9]
[5 7 9]


In [30]:
#행렬의 곱 -> x @ y / np.dot(x,y)

x2 = np.array([[1,2],[3,4]])
y2 = np.array([[5,6],[7,8]])

print(x2 @ y2)
print(np.dot(x2,y2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
